# Site settings
title: Yee's Blog
description: "personal blog"
url: "https://yeekal.github.io/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
highlighter: rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough","superscript"]


#highlight: true
source: .
destination: ./_site
permalink: /:title
paginate: 8    #how many items should be displayed in one page
paginate_path: /page:num/

# Default values
collections_dir: documents
collections:
  ompl:
    output: true
    permalink: /:collection/:name
  article:
    output: true
    permalink: /:collection/:name


#add front matter values to static files sometime
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.2"

# Options
reverse: false
