# Site settings
title: Yee's Blog
description: "personal blog"
url: "https://yeekal.github.io/"
author:
  name: "The Review Index"
  email: "dyutibarma@gmail.com"
  url: "https://thereviewindex.com"

# Build settings
baseurl: /YeeKal.github.io # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
reverse: false
