# Site settings
title: Yee's Blog
description: "personal blog"
url: "https://yeekal.github.io/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5    #how many items should be displayed in one page
paginate_path: /page:num/

# Default values
#add front matter values to static files sometime
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
reverse: false
